### ISSUE TITLE
I can‘t get an API key

### ISSUE THREAD

**Issue by 184026530** [jidomaps/unity_demo#8]
I  can‘t register through your home page and get an API key

**Comment by nicks258** [comment]
Did you find a solution for this??

**Comment by TheMakerMark** [comment]
@184026530 Beta API Keys are sent out on a rolling basis, the latest batch should be going out next week. If you still don't receive one by next week you can sign up again and reference your Github username.

**Comment by TheMakerMark** [comment]
@nicks258 I believe you received an API key in the October batch. If you didn't or haven't been able to use it in a sample project please email us.

**Comment by 184026530** [comment]
sorry ，I still haven't received it ,
I signed up again and i click the Get an API key , It pops up signed up .
the url is https://www.jidomaps.com/thank-you

**Comment by TheMakerMark** [comment]
You should have received an email on Dec. 28th with one. I resent the email to another one of your email addresses that you had signed up with. Feel free to email info-at-jidomaps.com directly if you still don't see the email.
